version: '3.3'

services:
  database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=erenBaba06
      - MSSQL_PID=Express
    ports:
      - 1453:1433

  webapi:
    build: .
    ports:
      - 1071:80
    depends_on:
      - database